### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by SchrodingersGat** [matmair/inventree-kom2#2]
After installing the plugin, and restarting the server:

![image](https://github.com/matmair/inventree-kom2/assets/10080325/7f1c8380-2154-4cc4-b343-e21da8e5a634)

![image](https://github.com/matmair/inventree-kom2/assets/10080325/258d6da4-67b1-4c7e-8ed7-87d6c6585036)

**Comment by matmair** [comment]
Looking into this

**Comment by matmair** [comment]
@SchrodingersGat was a silly mistake, installing `inventree-kom2==1.1a2` should fix that

**Comment by matmair** [comment]
@SchrodingersGat did you actually try this? Is it working with the mentioned version?
